### ISSUE TITLE
extlibs/ncepBUFR fails to compile on RHEL7 

### ISSUE THREAD

**Issue by akrherz** [Unidata/gempak#29]
ncepBUFR fails to compile on RHEL7.4 with current master.
```
gfortran -fno-second-underscore -fno-range-check -fd-lines-as-comments -I/home/gempak/GEMPAK7/gempak/include -I/home/gempak/GEMPAK7/os/linux64/include  -g -O   -F -o irev.f irev.F
f951: warning: command line option ‘-F-o’ is valid for C/C++/ObjC/ObjC++ but not for Fortran [enabled by default]
/tmp/ccLcGBSK.o: In function `irev_':
/home/akrherz/projects/gempak/extlibs/ncepBUFR/libncepBUFR/irev.F:72: multiple definition of `irev_'
/tmp/ccR8dDM8.o:/home/akrherz/projects/gempak/extlibs/ncepBUFR/libncepBUFR/irev.f:72: first defined here
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make[3]: *** [irev.f] Error 1
make[3]: Leaving directory `/usr/local/gempak/extlibs/ncepBUFR/v10.2.3'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/usr/local/gempak/extlibs/ncepBUFR'
```

I'll see if I can figure this out and submit a PR for it

**Comment by akrherz** [comment]
Hmmmm, `touch irev.f wrdlen.f` got me past this issue.  Boggling
